# -*- coding: utf-8 -*-
"""TansformersCode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kN578OEjIU73tApffrm1g4lVGEs0_p5S
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -U transformers --q
!pip install sentencepiece --q
!pip install tokenizers  --q
!pip install arabic-reshaper --q
!pip install python-bidi --q

# Commented out IPython magic to ensure Python compatibility.
import re
import time
import torch
import random
import numpy as np
import unicodedata
import pandas as pd
import torch.nn as nn
import arabic_reshaper
import torch.nn.functional as F
#import matplotlib.pyplot as plt
#from wordcloud import WordCloud
from collections import Counter
from transformers import BertModel
from bidi.algorithm import get_display
from bidi.algorithm import get_display
from torch.optim import SparseAdam, Adam
from transformers import  AutoModelForSequenceClassification, AutoTokenizer ,BertTokenizer, BertForSequenceClassification,AutoModel
#from imblearn.over_sampling import RandomOverSampler
from transformers import TrainingArguments, Trainer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, roc_curve, auc
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score,precision_recall_fscore_support
from transformers import AdamW, get_linear_schedule_with_warmup
from torch.utils.data import TensorDataset, DataLoader, RandomSampler, SequentialSampler
# %matplotlib inline

"""# **CamelBERT Without Overlap**"""

import pandas as pd

# Load your dataset
data = pd.read_csv('Dataset_after_augmentation.csv')

#without overlap
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
from torch.utils.data import Dataset, DataLoader
import numpy as np
from sklearn.model_selection import train_test_split
import torch.nn as nn
from sklearn.metrics import precision_recall_fscore_support

# Parameters and Model Initialization
model_name = "CAMeL-Lab/bert-base-arabic-camelbert-msa"
NUMBER_LABELS = 9  # Number of labels in your dataset
MAX_LENGTH = 512

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=NUMBER_LABELS)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

def tokenize_with_stride(texts, tokenizer, max_length=512):
    input_ids = []
    attention_mask = []
    overflow_to_sample_mapping = []
    for i, text in enumerate(texts):
        tokenized = tokenizer(
            text,
            max_length=max_length,
            truncation=True,
            return_overflowing_tokens=True,
            return_tensors="pt",
            padding="max_length"
        )
        # Extend the tokenized outputs
        input_ids.append(tokenized.input_ids)
        attention_mask.append(tokenized.attention_mask)
        # Map each chunk back to its original text's index
        overflow_to_sample_mapping.extend([i] * tokenized.input_ids.size(0))

    # Concatenate the lists into tensors
    input_ids = torch.cat(input_ids, dim=0)
    attention_mask = torch.cat(attention_mask, dim=0)
    print(f"Total Chunks: {len(input_ids)}")
    print(f"Mapping Size: {len(overflow_to_sample_mapping)}")  # Should match the total number of chunks

    return {
        'input_ids': input_ids,
        'attention_mask': attention_mask,
        'overflow_to_sample_mapping': overflow_to_sample_mapping
    }

# Example Dataset Preparation
X = list(data["col2"])  # Your texts
y = data.iloc[:, 1:].values  # Your labels

# Split Data
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Tokenize Data with Stride
train_encodings = tokenize_with_stride(X_train, tokenizer, MAX_LENGTH)
val_encodings = tokenize_with_stride(X_val, tokenizer, MAX_LENGTH)

class CustomDataset(Dataset):
    def __init__(self, encodings, labels=None):
        self.encodings = encodings
        self.labels = labels  # Ensure this is an array or a list

    def __getitem__(self, idx):
        item = {key: val[idx] for key, val in self.encodings.items() if key != 'overflow_to_sample_mapping'}
        if self.labels is not None:
            sample_idx = self.encodings['overflow_to_sample_mapping'][idx]
            item['labels'] = torch.tensor(self.labels[sample_idx], dtype=torch.float)
        return item

    def __len__(self):
        return len(self.encodings['input_ids'])

# Create Datasets and DataLoaders
train_dataset = CustomDataset(train_encodings, y_train)
val_dataset = CustomDataset(val_encodings, y_val)
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=16, shuffle=False)

# Training Loop
optimizer = torch.optim.AdamW(model.parameters(), lr=5e-5)
loss_fn = nn.BCEWithLogitsLoss()

for epoch in range(3):  # Example epoch count
    model.train()
    for batch in train_loader:
        optimizer.zero_grad()
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)
        outputs = model(input_ids, attention_mask=attention_mask)
        logits = outputs.logits
        loss = loss_fn(logits, labels)
        loss.backward()
        optimizer.step()
    print(f"Epoch {epoch} completed.")

    # Evaluation
    model.eval()
    all_predictions = []
    all_true_labels = []
    with torch.no_grad():
        for batch in val_loader:
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['labels'].to(device)
            outputs = model(input_ids, attention_mask=attention_mask)
            logits = outputs.logits
            probabilities = torch.sigmoid(logits)
            predictions = (probabilities > 0.5).int()
            all_predictions.append(predictions.cpu().numpy())
            all_true_labels.append(labels.cpu().numpy())

    # Concatenate all batches
    all_predictions = np.concatenate(all_predictions)
    all_true_labels = np.concatenate(all_true_labels)

    # Calculate Precision, Recall, and F1 Score
    precision, recall, f1, _ = precision_recall_fscore_support(all_true_labels, all_predictions, average='micro')
    print(f"Epoch {epoch} - Precision: {precision:.4f}, Recall: {recall:.4f}, F1 Score: {f1:.4f}")

"""# **CamelBERT With Overlap**"""

#with overlap
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
from torch.utils.data import Dataset, DataLoader
import numpy as np
from sklearn.model_selection import train_test_split
import torch.nn as nn
from sklearn.metrics import precision_recall_fscore_support

# Parameters and Model Initialization
model_name = "CAMeL-Lab/bert-base-arabic-camelbert-msa"
NUMBER_LABELS = 9  # Number of labels in your dataset
MAX_LENGTH = 512
STRIDE = 100  # Stride for tokenization

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=NUMBER_LABELS)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

def tokenize_with_stride(texts, tokenizer, max_length=512, stride=100):
    input_ids = []
    attention_mask = []
    overflow_to_sample_mapping = []
    for i, text in enumerate(texts):
        tokenized = tokenizer(
            text,
            max_length=max_length,
            truncation=True,
            stride=stride,
            return_overflowing_tokens=True,
            return_tensors="pt",
            padding="max_length"
        )
        # Extend the tokenized outputs
        input_ids.append(tokenized.input_ids)
        attention_mask.append(tokenized.attention_mask)
        # Map each chunk back to its original text's index
        overflow_to_sample_mapping.extend([i] * tokenized.input_ids.size(0))

    # Concatenate the lists into tensors
    input_ids = torch.cat(input_ids, dim=0)
    attention_mask = torch.cat(attention_mask, dim=0)
    print(f"Total Chunks: {len(input_ids)}")
    print(f"Mapping Size: {len(overflow_to_sample_mapping)}")  # Should match the total number of chunks

    return {
        'input_ids': input_ids,
        'attention_mask': attention_mask,
        'overflow_to_sample_mapping': overflow_to_sample_mapping
    }

# Example Dataset Preparation
X = list(data["col2"])  # Your texts
y = data.iloc[:, 1:].values  # Your labels

# Split Data
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Tokenize Data with Stride
train_encodings = tokenize_with_stride(X_train, tokenizer, MAX_LENGTH, STRIDE)
val_encodings = tokenize_with_stride(X_val, tokenizer, MAX_LENGTH, STRIDE)

class CustomDataset(Dataset):
    def __init__(self, encodings, labels=None):
        self.encodings = encodings
        self.labels = labels  # Ensure this is an array or a list

    def __getitem__(self, idx):
        item = {key: val[idx] for key, val in self.encodings.items() if key != 'overflow_to_sample_mapping'}
        if self.labels is not None:
            sample_idx = self.encodings['overflow_to_sample_mapping'][idx]
            item['labels'] = torch.tensor(self.labels[sample_idx], dtype=torch.float)
        return item

    def __len__(self):
        return len(self.encodings['input_ids'])

# Create Datasets and DataLoaders
train_dataset = CustomDataset(train_encodings, y_train)
val_dataset = CustomDataset(val_encodings, y_val)
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=16, shuffle=False)

# Training Loop
optimizer = torch.optim.AdamW(model.parameters(), lr=5e-5)
loss_fn = nn.BCEWithLogitsLoss()

for epoch in range(3):
    model.train()
    for batch in train_loader:
        optimizer.zero_grad()
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)
        outputs = model(input_ids, attention_mask=attention_mask)
        logits = outputs.logits
        loss = loss_fn(logits, labels)
        loss.backward()
        optimizer.step()
    print(f"Epoch {epoch} completed.")

    # Evaluation
    model.eval()
    all_predictions = []
    all_true_labels = []
    with torch.no_grad():
        for batch in val_loader:
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['labels'].to(device)
            outputs = model(input_ids, attention_mask=attention_mask)
            logits = outputs.logits
            probabilities = torch.sigmoid(logits)
            predictions = (probabilities > 0.5).int()
            all_predictions.append(predictions.cpu().numpy())
            all_true_labels.append(labels.cpu().numpy())

    # Concatenate all batches
    all_predictions = np.concatenate(all_predictions)
    all_true_labels = np.concatenate(all_true_labels)

    # Calculate Precision, Recall, and F1 Score
    precision, recall, f1, _ = precision_recall_fscore_support(all_true_labels, all_predictions, average='micro')
    print(f"Epoch {epoch} - Precision: {precision:.4f}, Recall: {recall:.4f}, F1 Score: {f1:.4f}")

from sklearn.metrics import multilabel_confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Assuming you have already trained your model and obtained predictions and true labels
# Calculate confusion matrices for each label
multilabel_cms = multilabel_confusion_matrix(all_true_labels, all_predictions)

# List of descriptive label names
label_names = [
    "User Consent",
    "Data Collection and Processing",
    "Data Retention",
    "Data Protection and Sharing",
    "User Rights",
    "Advertisements",
    "Breach Notification",
    "Responsibility"
]

# Plotting heatmaps for each label's confusion matrix
for i, label_name in enumerate(label_names):
    plt.figure(figsize=(4, 3))  # Adjusted figure size for better readability
    sns.heatmap(multilabel_cms[i], annot=True, fmt='d', cmap='Blues', cbar=False)
    plt.title(f'Confusion Matrix for {label_name}')
    plt.xlabel('Predicted Labels')
    plt.ylabel('True Labels')
    plt.xticks([0.5, 1.5], labels=['Negative', 'Positive'])  # Adjust labels as needed
    plt.yticks([0.5, 1.5], labels=['Negative', 'Positive'], rotation=0)  # Adjust rotation and labels
    plt.tight_layout()  # Adjust layout to make sure everything fits without overlapping
    plt.show()

"""# **AraBERT Without Overlap**"""

import pandas as pd

# Load your dataset
data = pd.read_csv('Dataset_after_augmentation.csv')

#with overlap
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
from torch.utils.data import Dataset, DataLoader
import numpy as np
from sklearn.model_selection import train_test_split
import torch.nn as nn
from sklearn.metrics import precision_recall_fscore_support

# Parameters and Model Initialization
model_name = "aubmindlab/bert-base-arabertv02"
NUMBER_LABELS = 9  # Number of labels in your dataset
MAX_LENGTH = 512

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=NUMBER_LABELS)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

def tokenize_with_stride(texts, tokenizer, max_length=512):
    input_ids = []
    attention_mask = []
    overflow_to_sample_mapping = []
    for i, text in enumerate(texts):
        tokenized = tokenizer(
            text,
            max_length=max_length,
            truncation=True,
            return_overflowing_tokens=True,
            return_tensors="pt",
            padding="max_length"
        )
        # Extend the tokenized outputs
        input_ids.append(tokenized.input_ids)
        attention_mask.append(tokenized.attention_mask)
        # Map each chunk back to its original text's index
        overflow_to_sample_mapping.extend([i] * tokenized.input_ids.size(0))

    # Concatenate the lists into tensors
    input_ids = torch.cat(input_ids, dim=0)
    attention_mask = torch.cat(attention_mask, dim=0)
    print(f"Total Chunks: {len(input_ids)}")
    print(f"Mapping Size: {len(overflow_to_sample_mapping)}")

    return {
        'input_ids': input_ids,
        'attention_mask': attention_mask,
        'overflow_to_sample_mapping': overflow_to_sample_mapping
    }

# Example Dataset Preparation
X = list(data["col2"])  # Your texts
y = data.iloc[:, 1:].values  # Your labels

# Split Data
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Tokenize Data with Stride
train_encodings = tokenize_with_stride(X_train, tokenizer, MAX_LENGTH)
val_encodings = tokenize_with_stride(X_val, tokenizer, MAX_LENGTH)

class CustomDataset(Dataset):
    def __init__(self, encodings, labels=None):
        self.encodings = encodings
        self.labels = labels  # Ensure this is an array or a list

    def __getitem__(self, idx):
        item = {key: val[idx] for key, val in self.encodings.items() if key != 'overflow_to_sample_mapping'}
        if self.labels is not None:
            sample_idx = self.encodings['overflow_to_sample_mapping'][idx]
            item['labels'] = torch.tensor(self.labels[sample_idx], dtype=torch.float)
        return item

    def __len__(self):
        return len(self.encodings['input_ids'])

# Create Datasets and DataLoaders
train_dataset = CustomDataset(train_encodings, y_train)
val_dataset = CustomDataset(val_encodings, y_val)
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=16, shuffle=False)

# Training Loop
optimizer = torch.optim.AdamW(model.parameters(), lr=5e-5)
loss_fn = nn.BCEWithLogitsLoss()

for epoch in range(3):  # Example epoch count
    model.train()
    for batch in train_loader:
        optimizer.zero_grad()
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)
        outputs = model(input_ids, attention_mask=attention_mask)
        logits = outputs.logits
        loss = loss_fn(logits, labels)
        loss.backward()
        optimizer.step()
    print(f"Epoch {epoch} completed.")

    # Evaluation
    model.eval()
    all_predictions = []
    all_true_labels = []
    with torch.no_grad():
        for batch in val_loader:
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['labels'].to(device)
            outputs = model(input_ids, attention_mask=attention_mask)
            logits = outputs.logits
            probabilities = torch.sigmoid(logits)
            predictions = (probabilities > 0.5).int()
            all_predictions.append(predictions.cpu().numpy())
            all_true_labels.append(labels.cpu().numpy())

    # Concatenate all batches
    all_predictions = np.concatenate(all_predictions)
    all_true_labels = np.concatenate(all_true_labels)

    # Calculate Precision, Recall, and F1 Score
    precision, recall, f1, _ = precision_recall_fscore_support(all_true_labels, all_predictions, average='micro')
    print(f"Epoch {epoch} - Precision: {precision:.4f}, Recall: {recall:.4f}, F1 Score: {f1:.4f}")

"""# **AraBERT With Overlap**"""

#with overlap
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
from torch.utils.data import Dataset, DataLoader
import numpy as np
from sklearn.model_selection import train_test_split
import torch.nn as nn
from sklearn.metrics import precision_recall_fscore_support

# Parameters and Model Initialization
model_name = "aubmindlab/bert-base-arabertv02"
NUMBER_LABELS = 9  # Number of labels in your dataset
MAX_LENGTH = 512
STRIDE = 100  # Stride for tokenization

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=NUMBER_LABELS)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

def tokenize_with_stride(texts, tokenizer, max_length=512, stride=100):
    input_ids = []
    attention_mask = []
    overflow_to_sample_mapping = []
    for i, text in enumerate(texts):
        tokenized = tokenizer(
            text,
            max_length=max_length,
            truncation=True,
            stride=stride,
            return_overflowing_tokens=True,
            return_tensors="pt",
            padding="max_length"
        )
        # Extend the tokenized outputs
        input_ids.append(tokenized.input_ids)
        attention_mask.append(tokenized.attention_mask)
        # Map each chunk back to its original text's index
        overflow_to_sample_mapping.extend([i] * tokenized.input_ids.size(0))

    # Concatenate the lists into tensors
    input_ids = torch.cat(input_ids, dim=0)
    attention_mask = torch.cat(attention_mask, dim=0)
    print(f"Total Chunks: {len(input_ids)}")
    print(f"Mapping Size: {len(overflow_to_sample_mapping)}")  # Should match the total number of chunks

    return {
        'input_ids': input_ids,
        'attention_mask': attention_mask,
        'overflow_to_sample_mapping': overflow_to_sample_mapping
    }

# Example Dataset Preparation
X = list(data["col2"])  # Your texts
y = data.iloc[:, 1:].values  # Your labels

# Split Data
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Tokenize Data with Stride
train_encodings = tokenize_with_stride(X_train, tokenizer, MAX_LENGTH, STRIDE)
val_encodings = tokenize_with_stride(X_val, tokenizer, MAX_LENGTH, STRIDE)

class CustomDataset(Dataset):
    def __init__(self, encodings, labels=None):
        self.encodings = encodings
        self.labels = labels  # Ensure this is an array or a list

    def __getitem__(self, idx):
        item = {key: val[idx] for key, val in self.encodings.items() if key != 'overflow_to_sample_mapping'}
        if self.labels is not None:
            sample_idx = self.encodings['overflow_to_sample_mapping'][idx]
            item['labels'] = torch.tensor(self.labels[sample_idx], dtype=torch.float)
        return item

    def __len__(self):
        return len(self.encodings['input_ids'])

# Create Datasets and DataLoaders
train_dataset = CustomDataset(train_encodings, y_train)
val_dataset = CustomDataset(val_encodings, y_val)
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=16, shuffle=False)

# Training Loop
optimizer = torch.optim.AdamW(model.parameters(), lr=5e-5)
loss_fn = nn.BCEWithLogitsLoss()

for epoch in range(3):
    model.train()
    for batch in train_loader:
        optimizer.zero_grad()
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)
        outputs = model(input_ids, attention_mask=attention_mask)
        logits = outputs.logits
        loss = loss_fn(logits, labels)
        loss.backward()
        optimizer.step()
    print(f"Epoch {epoch} completed.")

    # Evaluation
    model.eval()
    all_predictions = []
    all_true_labels = []
    with torch.no_grad():
        for batch in val_loader:
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['labels'].to(device)
            outputs = model(input_ids, attention_mask=attention_mask)
            logits = outputs.logits
            probabilities = torch.sigmoid(logits)
            predictions = (probabilities > 0.5).int()
            all_predictions.append(predictions.cpu().numpy())
            all_true_labels.append(labels.cpu().numpy())

    # Concatenate all batches
    all_predictions = np.concatenate(all_predictions)
    all_true_labels = np.concatenate(all_true_labels)

    # Calculate Precision, Recall, and F1 Score
    precision, recall, f1, _ = precision_recall_fscore_support(all_true_labels, all_predictions, average='micro')
    print(f"Epoch {epoch} - Precision: {precision:.4f}, Recall: {recall:.4f}, F1 Score: {f1:.4f}")